SELECT 
      II.ITEM_ID AS ITEM_ID
    , II.ITEM_NAME
    , II.RARITY
FROM ITEM_INFO II
LEFT JOIN ITEM_TREE CHILD ON II.ITEM_ID = CHILD.PARENT_ITEM_ID
WHERE CHILD.PARENT_ITEM_ID IS NULL
ORDER BY ITEM_ID DESC