SELECT
  YEAR(OS.SALES_DATE)  AS sales_year,
  MONTH(OS.SALES_DATE) AS sales_month,
  COUNT(DISTINCT OS.USER_ID) AS purchased_users,
  ROUND(
    COUNT(DISTINCT OS.USER_ID) 
    / 
    (SELECT COUNT(*) 
     FROM USER_INFO 
     WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'),
    1
  ) AS purchased_ratio
FROM USER_INFO UI
JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
WHERE UI.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY sales_year ASC, sales_month ASC;
