-- 코드를 작성해주세요
SELECT 
      FI2.ID
    , FNI.FISH_NAME      
    , FI.LENGTH
FROM (
    SELECT 
          FI.FISH_TYPE AS FISH_TYPE
        , MAX(FI.LENGTH) AS LENGTH
    FROM FISH_INFO FI
    GROUP BY FI.FISH_TYPE
    ORDER BY MAX(FI.LENGTH)
) AS FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
JOIN FISH_INFO FI2 ON FI.FISH_TYPE = FI2.FISH_TYPE AND FI.LENGTH = FI2.LENGTH