-- 코드를 입력하세요
SELECT 
        B.CATEGORY AS CATEGORY
      , SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE >= '2022-01-01'
AND SALES_DATE <= '2022-01-31'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC